name: Publish
on:
  push:
    branches:
      - master
    tags:
      - "v*.*.*"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    name: Python ${{ matrix.python-version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build and publish to pypi
        uses: JRubics/poetry-publish@v2.1
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}